#![cfg_attr(coverage_nightly, feature(coverage_attribute))]

pub mod catalogue;
pub mod common;
pub mod course;
pub mod course_manual;
pub mod feasibility;
pub mod intake;
pub mod language;
pub mod organigramme;
#[cfg(feature = "parser")]
pub mod parser;
pub mod preparatory;
pub mod prereq_override;
pub mod prereq_parse;
pub mod program;
pub mod program_manual;
pub mod rules;
pub mod transcript;
pub mod week;
pub mod weekly;

pub use catalogue::*;
pub use common::*;
pub use course::*;
pub use course_manual::*;
pub use feasibility::*;
pub use intake::*;
pub use language::*;
pub use organigramme::*;
#[cfg(feature = "parser")]
pub use parser::ParseError;
pub use preparatory::*;
pub use prereq_override::*;
pub use prereq_parse::*;
pub use program::*;
pub use program_manual::*;
pub use rules::*;
pub use transcript::*;
pub use week::*;
pub use weekly::*;
